GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons/102
###
DELETE http://localhost:3001/api/persons/6952750617508b4869776930
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jo",
    "number": "18-3412-225"
}
###
PUT http://localhost:3001/api/persons/6951a5a4e1c1df748ba54b5f
Content-Type: application/json

{
    "name": "Mario",
    "number": "31-2618225"
}

